function matrices = get_matrices(model, growth_rate)

model.build_matrices(growth_rate)
py.scipy.io.savemat('temp', py.dict( ...
    pyargs('A', matrices.A, ...
           'b', matrices.b, ...
           'row_signs', matrices.row_signs, ...
           'LB', matrices.LB, ...
           'UB', matrices.UB, ...
           'f', matrices.f, ...
           'col_names', matrices.col_names, ...
           'row_names', matrices.row_names)))
matrices = load(temp.mat)
